name: GitHub Actions Vercel Deploy

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
jobs:
  Test:
    if: github.event.pull_request.merged == true
    uses: MonicaLuongNZ/CISE_W102_03_SPEED/.github/workflows/ci.yml@main

  Deploy-Backend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [Test]
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        working-directory: ./backend
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        working-directory: ./backend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        working-directory: ./backend
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ./backend
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  Deploy-Frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [Test]
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Vercel CLI
        working-directory: ./frontend
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        working-directory: ./frontend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        working-directory: ./frontend
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ./frontend
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}